[package]
name = "tokenomics-simulator"
description = "Simulate trades, calculate various metrics, and predict user behaviour over different time intervals."
version = "0.1.5"
license = "MIT"
edition = "2021"
readme = "README.md"
authors = ["Slavik Pastushenko <slavpas@gmail.com>"]
keywords = [
  "tokenomics",
  "metrics",
  "analytics",
  "crypto",
  "blockchain",
  "simulator",
]
repository = "https://github.com/simetrics-io/tokenomics-simulator-rs"
documentation = "https://docs.rs/tokenomics-simulator"
exclude = [".github/**"]

[lib]
name = "tokenomics_simulator"
path = "src/lib.rs"

[dependencies]
chrono = { version = "0.4.39", features = ["serde"] }
rand = "0.8.5"
rust_decimal = { version = "1.36.0" }
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
twox-hash = "2.1.0"
uuid = { version = "1.12.1", features = ["serde", "v4"] }
