[package]
name = "tokenomics-simulator"
description = "Simulate trades, calculate various metrics, and visualise the results over different time intervals."
version = "0.1.0"
license = "MIT"
edition = "2021"
readme = "README.md"
authors = ["Slavik Pastushenko <slavpas@gmail.com>"]
keywords = ["tokenomics", "crypto", "blockchain", "simulator"]
repository = "https://github.com/TokenomicsHub/tokenomics-simulator-rs"
documentation = "https://docs.rs/tokenomics-simulator"

[lib]
name = "tokenomics_simulator"
path = "src/lib.rs"

[dependencies]
chrono = { version = "0.4.39", features = ["serde"] }
rand = "0.8.5"
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
twox-hash = "2.1.0"
uuid = { version = "1.12.1", features = ["serde", "v4"] }
