[package]
name = "tokenomics-simulator"
description = "Simulate trades, calculate various metrics, and predict user behaviour over different time intervals."
version = "0.1.21"
license = "Apache-2.0"
edition = "2021"
readme = "README.md"
homepage = "https://simetrics.io"
authors = ["simetrics <info@simetrics.io>"]
keywords = ["tokenomics", "metrics", "analytics", "crypto", "simulator"]
repository = "https://github.com/simetrics-io/tokenomics-simulator-rs"
documentation = "https://docs.rs/tokenomics-simulator"
exclude = [".github/**", "examples/**"]

[lib]
name = "tokenomics_simulator"
path = "src/lib.rs"

[dependencies]
chrono = { version = "0.4.39", features = ["serde"] }
rand = "0.8.5"
rust_decimal = { version = "1.36.0", features = ["maths"] }
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.11"
twox-hash = "2.1.0"
uuid = { version = "1.12.1", features = ["serde", "v4"] }

[dev-dependencies]
clap = { version = "4.5.27", features = ["derive"] }

[[example]]
name = "cli"
path = "examples/cli.rs"

[[example]]
name = "basic_simulation"
path = "examples/basic_simulation.rs"

[[example]]
name = "custom_token"
path = "examples/custom_token.rs"

[[example]]
name = "advanced_options"
path = "examples/advanced_options.rs"

[[example]]
name = "multiple_simulations"
path = "examples/multiple_simulations.rs"
